# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('air_id', models.IntegerField(primary_key=True, serialize=False)),
                ('carrier_code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AirlineFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.IntegerField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Airline')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('port_id', models.IntegerField(primary_key=True, serialize=False)),
                ('port_code', models.CharField(max_length=10)),
                ('state_code', models.CharField(max_length=10)),
                ('city_name', models.CharField(max_length=30)),
                ('state_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Delayed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.PositiveIntegerField()),
                ('weather', models.PositiveIntegerField()),
                ('nas', models.PositiveIntegerField()),
                ('security', models.PositiveIntegerField()),
                ('late_aircraft', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs_time', models.DateTimeField()),
                ('actual_time', models.DateTimeField()),
                ('delay', models.IntegerField()),
                ('is_delay', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('week', models.PositiveIntegerField()),
                ('distance', models.PositiveIntegerField()),
                ('tail_num', models.CharField(max_length=30)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancel_code', models.CharField(max_length=10)),
                ('is_diverted', models.BooleanField(default=False)),
                ('crs_elapsed_time', models.PositiveIntegerField()),
                ('actual_elapsed_time', models.PositiveIntegerField()),
                ('air_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.AirlineFlight')),
                ('arr_perf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='analysis.Performance')),
                ('dep_perf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='analysis.Performance')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='analysis.Airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='analysis.Airport')),
            ],
        ),
        migrations.AddField(
            model_name='delayed',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Trip'),
        ),
    ]
